version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    networks:
      - devnet

networks:
  devnet:
    external: true
